# Generated by Django 5.2.1 on 2025-06-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
