# Generated by Django 5.2.1 on 2025-06-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0002_alter_candles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
