# Generated by Django 5.2.1 on 2025-06-13 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0003_alter_candles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
