# Generated by Django 5.2.1 on 2025-06-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0004_alter_candles_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candles',
            name='created_at',
        ),
    ]
